### ISSUE TITLE
Feature request: Discord Webhook integration

### ISSUE THREAD

**Issue by skikibobski** [imTHAI/docker-qbittorrent-filebot#1]
I've been unable to add variables to fb.sh. I'm not very familiar with any coding, but I'm guessing you're pulling a new file from online, or somewhere locally, everytime the container starts up, and any changes I've made are thereby erased?
I would like to be able to call Discord when the AMC script has finished processing a file.
I guess it would only be a matter of adding --def discord="DISCORD_WEBHOOK" and then add another user-defined variable for the container.
If there is a way to add parameters to the .sh file that I've missed, please feel free to enlighten me as it would spare you the time to update.
Appreciate your work on this!

**Comment by imTHAI** [comment]
I believe it's solved. Don't hesitate to come back to me if I can still help.
Hv a good day
