### ISSUE TITLE
7z failing all extractions

### ISSUE THREAD

**Issue by itsnotwebby** [imTHAI/docker-qbittorrent-filebot#2]
Recently I noticed filebot failing to extract anything.  At best it would create an empty folder within source folder but that was it.  Only info in the log said "failed (2)".  No further information.

In working with the dev of FB we confirmed that even invoking fb manually 7z would not extract.  
Changing it to use unrar instead of 7z worked right away.  
With that said, I had to do a few things.
First I had to add unrar via nerdtools plugin.  Maybe I didn't HAVE to but I'm not sure unrar comes in unraid.
From there I had to tell FB to use unrar
```
filebot -script fn:properties --def net.filebot.archive.unrar=/path/to/unrar
``` 
The path unrar was located
```
/usr/bin/unrar
``` 

Now because Qbittorrent calls FB as a different user than I am, I had to copy the newly updated properties using this.

```
cp -v /filebot/data/0/system.properties /filebot/data/99/
``` 

I've tested a few items, especially ones that failed before, and this change has worked for me.
I am not educated enough to diagnose why this was happening, and I really had to pester the dev over at FB to help me out, so all this work is to credit of @rednoah over in the filebot discord.

**Comment by imTHAI** [comment]
Hello,
Why did you need to install unrar on unraid since we run filebot inside a container ? And unrar is available in the container.

**Comment by itsnotwebby** [comment]
I'm not sure that I needed to, and I specifically said that in the initial post but I couldn't find any support documentation for this container. 
But the ISSUE, the reason I put all that time into the post is that 7z was failing every single extraction.

I'm not a developer.  I'm just an end user trying to provide some help or insight into how to solve the issue in the meantime for every other end user experiencing the same problem.

**Comment by rednoah** [comment]
FileBot doesn't use `unrar` unless explicitly configured to do so. Adding this line to the `Dockerfile` should do the trick:
```
ENV FILEBOT_OPTS=-Dnet.filebot.archive.unrar=/usr/bin/unrar
```
Alternatively, adding `*.rar` support to `7z` is also on option. On Debian, that would be done by installing the `p7zip-rar` package.

**Comment by imTHAI** [comment]
So I went with the  environment variable solution of rednoah. Thanks to him.
@itsnotwebby give it a try and let us know.
