### ISSUE TITLE
Problème lien symbolique .

### ISSUE THREAD

**Issue by ppo852** [imTHAI/docker-qbittorrent-filebot#4]
Bonjour j'ai essayé d'utiliser ton docker  qui a l'air de bien fonctionner à part le problème avec les liens symboliques qui sont morts j'aurais voulu savoir si tu avais prévu de corrigé ce petit bug car à part ça tout fonctionne bien et je n'ai pas trouvé d'autres d'autres docker  comme le tien merci

**Comment by imTHAI** [comment]
Hello, 
De quels liens symboliques s'agit-il ?

**Comment by imTHAI** [comment]
Haaaa. Oui j'avais testé au tout début et j'avais eu des erreurs. Mais je ne sais plus les quelles, je ne jurerais pas que c'était la même. J'ai pensé que c'était lié au fait que c'était entre deux partitions/disques différents. 
Je vais rester et gratter un peu le sujet dès que je peux, et te reviens.

**Comment by imTHAI** [comment]
Je viens de tester et ça m'a rafraichit la mémoire sur le sujet.

- l'action **hardlink** ne fonctionne pas si on est entre deux FS différent ce qui est mon cas et le tien. D'abord parce qu'avec unraid on met souvent le downloads folder sur un pool dédié, donc différent du array de data sur lequel on stocke sa Library. Mais en plus parce qu'ici c'est un container docker et que les volumes sont d'emblée considérés comme des fs différents. (ou alors il faut que tu regroupe tes folder input/output sous un meme point de montage ce qui est faisable mais peu pratique).
- L'action **symlink** fonctionne. C'est le fichier dans la Library qui sera le symlink et qui pointe vers le "vrai" fichier dans le folder downloads. Le hic c'est que mon Plex ne le détecte pas. (confirmé par des discussions sur le net).
- Il reste l'action **keeplink** qui est un concept filebot, et qui correspond à un symlink inversé. Le fichier est mis dans la Library et le symlink est créé dans le folder downloads. Et a priori ça fonctionne bien, j'avais peur que qbittorrent ne le comprenne pas en tant que fichier intègre mais si. Le soucis en faisant ça, c'est que ça va constamment _spin on_ les disques de ton array puisque tous tes fichiers torrents vont, en vrai, se trouver là. Par contre tu peux ainsi partager TOUTE ta bibliothèque et avoir des centaines de torrent constamment en seed 😁

**Comment by ppo852** [comment]
j'ai trouvé pourquoi mon symlink ne fonctionné pas dans mon docker j'avais mis en chemin /home/seed/torrent/media/test:/media   et     /home/seed/torrent/downloads/test:/downloads au lieu de  /home/seed/torrent/test/media:/media   et     /home/seed/torrent/test/downloads:/downloads et  la ca fonctionne, j'ai fait un teste sur mon autre serveur avec emby en fonction et sa  fonctionne coll  mais sur mon nouveau serveur  emby  me le détecte mais me dit fichier introuvable , bizarre mais la ces plus le même problème merci encore pour ton docker
