### ISSUE TITLE
Music is being excluded

### ISSUE THREAD

**Issue by itsnotwebby** [imTHAI/docker-qbittorrent-filebot#5]
I cannot get filebot to manage music in the same way as it manages movies and tv.  
In the logs I can see this:
Parameter: excludeList = /data/filebot/amc-exlude-list.txt
Parameter: unsorted = y
Parameter: music = /media/y
Parameter: musicFormat = /media/music/{artist} - {t}
Parameter: artwork = /media/y
Parameter: movieFormat = /media/movies/{plex.tail}
Parameter: seriesFormat = /media/tv/{plex.tail}
Parameter: animeFormat = /media/animes/{n}/{e.pad(3)} - {t}
Parameter: ut_dir = /downloads/complete/Adele - 21 Limited Edition Flac
Parameter: ut_title = Adele - 21 Limited Edition Flac
Parameter: ut_label = 
Use excludes: /data/filebot/amc-exlude-list.txt (2089)
No files selected for processing
Done ¯\_(ツ)_/¯

But no files were processed as it shows, even though I have music set to yes.  Thats the only help I've found on the filebot forum, adding 
music=y \

**Comment by imTHAI** [comment]
It should be fixed with 650f727
Try and tell me.

**Comment by imTHAI** [comment]
> This works but dumps all music into a single folder, regardless of artist. But it works!

I just tried: Filebot put it in the correct folder and correct way (Artist/Album name)

```
COPY] from [/downloads/Stromae - Multitude (2022)/01-stromae-invaincu-repack.mp3] to [/media/music/Stromae/Multitude/01 - Invaincu.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/02-stromae-sante-repack.mp3] to [/media/music/Stromae/Multitude/02 - Santé.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/03-stromae-la_solassitude-repack.mp3] to [/media/music/Stromae/Multitude/03 - La Solassitude.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/04-stromae-fils_de_joie-repack.mp3] to [/media/music/Stromae/Multitude/04 - Fils de joie.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/05-stromae-lenfer-repack.mp3] to [/media/music/Stromae/Multitude/05 - L'enfer.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/06-stromae-cest_que_du_bonheur-repack.mp3] to [/media/music/Stromae/Multitude/06 - C'est que du bonheur.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/07-stromae-pas_vraiment-repack.mp3] to [/media/music/Stromae/Multitude/07 - Pas vraiment.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/08-stromae-riez-repack.mp3] to [/media/music/Stromae/Multitude/08 - Riez.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/09-stromae-mon_amour-repack.mp3] to [/media/music/Stromae/Multitude/09 - Mon amour.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/10-stromae-declaration-repack.mp3] to [/media/music/Stromae/Multitude/10 - Déclaration.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/11-stromae-mauvaise_journee-repack.mp3] to [/media/music/Stromae/Multitude/11 - Mauvaise journée.mp3]
[COPY] from [/downloads/Stromae - Multitude (2022)/12-stromae-bonne_journee-repack.mp3] to [/media/music/Stromae/Multitude/12 - Bonne journée.mp3]
Processed 12 files
Done ヾ(＠⌒ー⌒＠)ノ
```

If you want diffently, you have to modify this var
`musicFormat = /media/music/{artist} - {t}` in the script

**Comment by itsnotwebby** [comment]
### This is my Log

Group: {Music=/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT} => [01-pink_floyd-speak_to_me.flac, 02-pink_floyd-breathe.flac, 03-pink_floyd-on_the_run.flac, 04-pink_floyd-time.flac, 05-pink_floyd-the_great_gig_in_the_sky.flac, 06-pink_floyd-money.flac, 07-pink_floyd-us_and_them.flac, 08-pink_floyd-any_colour_you_like.flac, 09-pink_floyd-brain_damage.flac, 10-pink_floyd-eclipse.flac]
Rename music using [ID3 Tags]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/01-pink_floyd-speak_to_me.flac] to [/media/music/Pink Floyd - Speak To Me.flac]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/02-pink_floyd-breathe.flac] to [/media/music/Pink Floyd - Breathe.flac]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/03-pink_floyd-on_the_run.flac] to [/media/music/Pink Floyd - On The Run.flac]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/04-pink_floyd-time.flac] to [/media/music/Pink Floyd - Time.flac]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/05-pink_floyd-the_great_gig_in_the_sky.flac] to [/media/music/Pink Floyd - The Great Gig In The Sky.flac]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/06-pink_floyd-money.flac] to [/media/music/Pink Floyd - Money.flac]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/07-pink_floyd-us_and_them.flac] to [/media/music/Pink Floyd - Us And Them.flac]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/08-pink_floyd-any_colour_you_like.flac] to [/media/music/Pink Floyd - Any Colour You Like.flac]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/09-pink_floyd-brain_damage.flac] to [/media/music/Pink Floyd - Brain Damage.flac]
[COPY] from [/downloads/complete/Pink_Floyd-The_Dark_Side_Of_The_Moon-Remastered-CD-FLAC-2003-PERFECT/10-pink_floyd-eclipse.flac] to [/media/music/Pink Floyd - Eclipse.flac]
Processed 10 files
Done ヾ(＠⌒ー⌒＠)ノ


### This is what is set in the container
music/{artist} - {t}


### This is what is in the script
musicFormat=/media/"$MUSIC_FORMAT" \

**Comment by itsnotwebby** [comment]
It looks like plex can still manage the files being all in a single folder.  So although its not looking great, the issue is solved.
