### ISSUE TITLE
Filebot sometimes skipping movies. How can I manually re-run the filebot script?

### ISSUE THREAD

**Issue by Singularity9** [imTHAI/docker-qbittorrent-filebot#7]

**Comment by imTHAI** [comment]
That filebot can’t identify the media, I can imagine that could happen. But to skip the media altogether, I don’t see how that’s possible. At least it never happened to me. 
What does the logs tell ?

You always can run the script manually from the shell in the container.
For example:
`/data/filebot/fb.sh /downloads/The.Acolyte.S01E05.MULTI.HDR.2160p.WEB.H265-HiggsBoson`

Rmq: If you left the excludeList parameter, you must first remove the media from the exclude list.

**Comment by Singularity9** [comment]
I believe that the media is properly formatted, I've had this happen every time I download many Movies or TV Shows at once. If I do it one at a time then there is no problem. I also see that the Movies/TV Shows that were skipped were not added to the exclude list, so if I were to run Filebot for the entire directory then it should detect all the missing ones and copy them over. My only concern with that I have both TV Shows and Movies mixed into the same download directory, can filebot differentiate between the two types if I call it or do I need to call filebot with a specific "TV Show" parameter and then again call it with a "Movie" parameter?

**Comment by imTHAI** [comment]
No, no parameters to specify, filebot can identify if it is a serie or a movie.

**Comment by Singularity9** [comment]
Great! I just ran "/data/filebot/fb.sh /downloads/"
and it detected all the skipped shows/movies

Thank you

I BELIEVE that I may have ran out of Cache space, and that's why it failed the first time.

**Comment by Singularity9** [comment]
Perhaps there could be a UI option to "Re-run Filebot" calling /data/filebot/fb.sh /downloads/ for situations like these
