### ISSUE TITLE
Filebot not automatically running

### ISSUE THREAD

**Issue by trickolon** [imTHAI/docker-qbittorrent-filebot#8]
Hi, I recently updated to v4.6.5

After the torrent is finished, it does not seem to run filebot anymore. There is nothing in the logs showing errors

**Comment by imTHAI** [comment]
Hello,
On my side I got some right error messages. Something must hv been changed upstream. 
I fixed it with c634da4
Try it and let me know.

**Comment by imTHAI** [comment]
> Do I run this in the qbitorrent console?
> or which file do I add this to?

c634da4 is just how I fixed the problem.
Now you, you just have to update your container with the new image I have pushed on the docker hub. And then try if you still have the problem.

**Comment by trickolon** [comment]
works perfectly! Thanks!
