### ISSUE TITLE
Delete Files left behind

### ISSUE THREAD

**Issue by trickolon** [imTHAI/docker-qbittorrent-filebot#9]
Hi,

Just wondering is there a way to delete and files/folders remaining after the torrent is finished and filebot has renamed and moved the content?
 
I've tried using --def clean=y Delete left behind empty folders and clutter files in the past after editing the fb.sh file and making sure it says 1 on the top.

It shows Clean = y in the parameters just still leaves behind the clutter files.

![image](https://github.com/user-attachments/assets/64d6eb66-02fd-48d9-9438-ff1a2704b32d)

**Comment by rednoah** [comment]
OP forgot the link the complete context on the issue:
https://www.filebot.net/forums/viewtopic.php?t=14374


Notable `amc script` issues:
* `fb.sh` specifies `--def artwork/media/y` which is always incorrect / false. The correct usage is `--def artwork=y` or `--def artwork=n` to enable / disable the `artwork` feature
* `fb.sh` does specify `--def ut_dir` but not `--def ut_kind` which leads to various issues including `--def clean=y` having no effect. The correct usage is `--def "ut_kind=multi" "ut_dir=/path/to/input"`. See [Setup for qBittorrent on Linux](https://www.filebot.net/forums/viewtopic.php?p=9774#p9774) for details.

**Comment by trickolon** [comment]
> OP forgot the link the complete context on the issue: https://www.filebot.net/forums/viewtopic.php?t=14374
> 
> Notable `amc script` issues:
> 
> * `fb.sh` specifies `--def artwork/media/y` which is always incorrect / false. The correct usage is `--def artwork=y` or `--def artwork=n` to enable / disable the `artwork` feature
> * `fb.sh` does specify `--def ut_dir` but not `--def ut_kind` which leads to various issues including `--def clean=y` having no effect. The correct usage is `--def "ut_kind=multi" "ut_dir=/path/to/input"`. See [Setup for qBittorrent on Linux](https://www.filebot.net/forums/viewtopic.php?p=9774#p9774) for details.

So this is the current fb.sh file contents - do i just add `--def "ut_kind=multi" "ut_dir=/path/to/input to the fb.sh file?

custom=1

/filebot/filebot.sh \
-script fn:amc \
--output /media \
--lang "$FILEBOT_LANG" \
--action "$FILEBOT_ACTION" \
--conflict "$FILEBOT_CONFLICT" \
--log-file /data/filebot/filebot.log \
--def excludeList=/data/filebot/amc-exlude-list.txt \
--def clean=y \
-non-strict \
--def \
unsorted=y \
music="$FILEBOT_PROCESS_MUSIC" \
musicFormat=/media/"$MUSIC_FORMAT" \
artwork=/media/"$FILEBOT_ARTWORK" \
movieFormat=/media/"$MOVIE_FORMAT" \
seriesFormat=/media/"$SERIE_FORMAT" \
animeFormat=/media/"$ANIME_FORMAT" \
ut_dir="$1" \
ut_title="$2" \
ut_label="$3"

**Comment by imTHAI** [comment]
Hello,
I've modified the script fb.sh following rednoah’s always appreciated comments: I've corrected the typo regarding the artwork env. var et added the ut_kind one.

**Comment by rednoah** [comment]
Changes look good. Thanks for maintaining. Cheers.
